services:
  - type: web
    name: hr-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_api.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WATSONX_API_KEY
        sync: false
      - key: WATSONX_PROJECT_ID
        sync: false
      - key: WATSONX_URL
        sync: false
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: CHROMA_PERSIST_DIRECTORY
        value: /opt/render/project/src/embeddings
